name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: presetup
      run: sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-sound1.2-dev
    - name: setup
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
